# DigitalOcean App Platform Specification
# This file defines the deployment configuration for the Zid Integration Service

name: zid-integration-service
region: fra

services:
- name: api
  source_dir: /
  github:
    repo: samerzmd/zid-integration
    branch: master
    deploy_on_push: true
  
  build_command: |
    pip install --upgrade pip
    pip install -r requirements.txt
  
  run_command: |
    alembic upgrade head
    uvicorn app.main:app --host 0.0.0.0 --port $PORT
  
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  
  routes:
  - path: /
  
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ZID_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ZID_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ZID_REDIRECT_URI
    scope: RUN_AND_BUILD_TIME
    value: https://zid-s7xi6.ondigitalocean.app/auth/callback
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ENCRYPTION_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: LOG_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: INFO
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "8080"

# Database configuration (managed databases)
databases:
- name: zid-postgres
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb
  num_nodes: 1

- name: zid-redis
  engine: REDIS
  version: "7"
  size: db-s-1vcpu-1gb

# Jobs for database migrations and maintenance
jobs:
- name: migrate
  source_dir: /
  github:
    repo: samerzmd/zid-integration
    branch: master
  
  build_command: |
    pip install --upgrade pip
    pip install -r requirements.txt
  
  run_command: alembic upgrade head
  
  environment_slug: python
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET

# Alerts configuration
alerts:
- rule: CPU_UTILIZATION
  disabled: false
  value: 80
- rule: MEM_UTILIZATION
  disabled: false
  value: 80
- rule: RESTART_COUNT
  disabled: false
  value: 5