
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://zid_user:zid_password@db:5432/zid_db
      - ZID_CLIENT_ID=${ZID_CLIENT_ID}
      - ZID_CLIENT_SECRET=${ZID_CLIENT_SECRET}
      - ZID_REDIRECT_URI=${ZID_REDIRECT_URI}
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=zid_user
      - POSTGRES_PASSWORD=zid_password
      - POSTGRES_DB=zid_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: .
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://zid_user:zid_password@db:5432/zid_db
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: